/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customerlist;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.*;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author amey1
 */
public class CustomerGUI extends javax.swing.JFrame {

    Customer obj;
    LinkedList <Customer> ls;
    /**
     * Creates new form CustomerGUI
     */
    public CustomerGUI() {
        super("Customer List");
        initComponents();
        ls=new LinkedList <Customer>();
        addWindowListener(new WindowAdapter()
	{
            @Override
            public void windowClosing(WindowEvent e)
            {
				//close();
                try 
                {
                    FileOutputStream fo;
                    ObjectOutputStream oo;
                    fo=new FileOutputStream("CustomerList_DoNotDelete.amey");
                    oo=new ObjectOutputStream(fo);
                    oo.writeObject(ls);
                    fo.close();
                    oo.close();
                } 
                catch (FileNotFoundException ex) 
                {
                    JOptionPane.showMessageDialog(null,"Unable to create file...!!!"
                        + "\nTry giving it another shot!");
                } 
                catch (IOException ex) 
                {
                    JOptionPane.showMessageDialog(null,"Unable to write to the file...!!!"
                        + "\nTry giving it another shot!");
                }
		System.exit(0);
            }
        });
        //open
        openCustomer();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Customer List", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/PicsArt_06-12-03.34.29.jpg"))); // NOI18N

        jLabel2.setText("Customer No. :");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel3.setText("Customer Name :");

        jLabel4.setText("Phone No. :");

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel5.setText("Address :");

        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });

        jLabel6.setText("No. of Machines :");

        jLabel7.setText("No. of Batteries :");

        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel8.setText("Type of Machine :");

        jLabel9.setText("Type of Batteries :");

        jLabel10.setText("Month of Servicing :");

        jLabel11.setText("AMC Amount in Rupees :");

        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });

        jTextField12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField12FocusLost(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel12.setText("List of customers in searched Month :");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(22, 22, 22)
                        .addComponent(jTextField11)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jMenu1.setText("New");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu5.setText("Save");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu2.setText("Edit");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Delete");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Search");

        jMenuItem1.setText("By Customer No");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("By Customer Name");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("By Month");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    public Customer searchByName(String nm)
    {
        //openCustomer();
        Customer tmp=null;
        int i=0,n=ls.size();
        System.out.println("LinkedList size "+n);
	while(i<n)
	{
            tmp=(Customer)ls.get(i);
            if(nm.equals(tmp.cnm))
                break;
            i++;
	}
        if(i==n)
        {
            JOptionPane.showMessageDialog(null,"There is no such name "
                    + "in the Database!\nPlease enter a valid Customer Name");
            tmp=null;
        }
        System.out.println(tmp.toString());
        return tmp;
    }
    
    public Customer searchByNo(int no)
    {
        //openCustomer();
        Customer tmp=null;
        int i=0,n=ls.size();
        System.out.println("LinkedList size "+n);
	while(i<n)
	{
            tmp=ls.get(i);
            if(no==tmp.cno)
                break;
            i++;
	}
        if(i==n)
        {
            JOptionPane.showMessageDialog(null,"There is no such Number "
                    + "in the Database!\nPlease enter a valid Customer Number");
            tmp=null;
        }
        return tmp;
    }
    
    public void openCustomer()
    {
        try
        {
            FileInputStream fi;
            ObjectInputStream oi;
            fi=new FileInputStream("CustomerList_DoNotDelete.amey");
            oi=new ObjectInputStream(fi);
            ls=(LinkedList <Customer>) oi.readObject();
            System.out.println("LinkedList size "+ls.size());
            fi.close();
            oi.close();
        }
        catch(IOException | ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(null,"Unable to find file...!!!"
                    + "\nRecreating the file...");
            try 
            {
                FileOutputStream fo=null;
                ObjectOutputStream oo=null;
                fo=new FileOutputStream("CustomerList_DoNotDelete.amey");
                oo=new ObjectOutputStream(fo);
                //oo.writeObject(ls);
                fo.close();
                oo.close();
            } 
            catch (FileNotFoundException ex) 
            {
                JOptionPane.showMessageDialog(null,"Unable to create file...!!!"
                        + "\nTry giving it another shot!");
            } 
            catch (IOException ex) 
            {
                JOptionPane.showMessageDialog(null,"Unable to write to the file...!!!"
                        + "\nTry giving it another shot!");
            }
            JOptionPane.showMessageDialog(null,"File is recreated!");
                    
        }
    }
    
    public void writeCustomer()
    {
        int cno=0,cmno=0,cbno=0,camcamnt=0;
        String cphno="";
        String cnm="",caddr="",cmtype="",cbtype="",cmonth="";
        try
        {
            cno=Integer.parseInt(jTextField1.getText())-1;
            cnm=jTextField2.getText();
            cphno=(jTextField3.getText());
            caddr=jTextArea2.getText();
            cmno=Integer.parseInt(jTextField6.getText());
            cbno=Integer.parseInt(jTextField7.getText());
            cmtype=jTextField8.getText();
            cbtype=jTextField9.getText();
            cmonth=jTextField12.getText();
            camcamnt=Integer.parseInt(jTextField11.getText());
        }
        catch(NumberFormatException e){}
        ls.add(new Customer(cno,cphno,cmno,cbno,camcamnt,cnm,
                caddr,cmtype,cbtype,cmonth));
        System.out.println(new Customer(cno,cphno,cmno,cbno,camcamnt,cnm,
                caddr,cmtype,cbtype,cmonth).toString());
        System.out.println("LinkedList size "+ls.size());
        
    }
    
    public void deleteCustomer(String s)
    {
        Customer tmp=searchByName(s);
        ls.remove(tmp.cno);
        
    }
    
    public void setTextGUI(Customer tmp)
    {
        if(tmp==null)
            tmp=new Customer();
        jTextField1.setText(""+(tmp.cno+1));
        jTextField2.setText(tmp.cnm);
        jTextField3.setText(""+tmp.cphno);
        jTextField6.setText(""+tmp.cmno);
        jTextField7.setText(""+tmp.cbno);
        jTextField8.setText(tmp.cmtype);
        jTextField9.setText(tmp.cbtype);
        jTextArea2.setText(tmp.caddr);
        jTextField12.setText(tmp.cmonth);
        jTextField11.setText(""+tmp.camcamnt);
    }
    
    public void setAllEditable(Boolean b)
    {
        jTextField1.setEditable(b);
        jTextField2.setEditable(b);
        jTextField3.setEditable(b);
        jTextField6.setEditable(b);
        jTextField7.setEditable(b);
        jTextField8.setEditable(b);
        jTextField9.setEditable(b);
        jTextArea2.setEditable(b);
        jTextField12.setEditable(b);
        jTextField11.setEditable(b);
    }
    
    public boolean isInteger( String input ) 
    { 
        try 
        {
            Integer.parseInt( input );
            return true; 
        }
        catch( NumberFormatException e ) 
        { 
            return false;
        }
    } 
    
    public boolean isLong( String input ) 
    { 
        try 
        {
            long tmp = Long.parseLong( input );
            int i=0;
            while((tmp/=10)>1)
                i++;
            if(i==9)
                return true; 
            else
                return false;
        }
        catch( NumberFormatException e ) 
        { 
            return false;
        }
    } 
    
    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        //save
        writeCustomer();
        JOptionPane.showMessageDialog(null,"Saved...!!!\nCustomer is added"
                + " to the list");
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        //edit
        String nm=JOptionPane.showInputDialog(null,"Enter a valid Customer Name :-");
        Customer t=searchByName(nm);
        setTextGUI(t);
        setAllEditable(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        //new
        setAllEditable(true);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextArea1.setText("");
        jTextArea2.setText("");
        jTextField12.setText("");
        jTextField11.setText("");
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
        int no;
        String tmp=JOptionPane.showInputDialog(null,"Enter "
                    + "Customer No :-");
        try
        {
            no=Integer.parseInt(tmp);
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid Number..!!");
            no=0;
        }
        Customer tm=searchByNo(no);
        setTextGUI(tm);
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //search by no
        int no;
        try
        {
            no=Integer.parseInt(JOptionPane.showInputDialog(null,"Enter "
                    + "Customer No :-"));
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid Number..!!");
            no=0;
        }
        Customer tm=searchByNo(no-1);
        setTextGUI(tm);
        setAllEditable(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        deleteCustomer(JOptionPane.showInputDialog(null,"Enter a valid Customer Name :-"));
        JOptionPane.showMessageDialog(null,"Customer is successfuly deleted from the list!");
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        //search by name
        Customer t=searchByName(JOptionPane.showInputDialog(null,"Enter a valid Customer Name :-"));
        setTextGUI(t);
        setAllEditable(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        //check phone no
            if(isLong(jTextField3.getText()) == false)
                jTextField3.setBackground(Color.red);
            else
                jTextField3.setBackground(Color.white);
    
        
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        // TODO add your handling code here:
            if(isInteger(jTextField6.getText()) == false)
                jTextField6.setBackground(Color.red);
            else
                jTextField6.setBackground(Color.white);
        
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:
            if(isInteger(jTextField7.getText()) == false)
                jTextField7.setBackground(Color.red);
            else
                jTextField7.setBackground(Color.white);
        
    }//GEN-LAST:event_jTextField7FocusLost

    public boolean verifyMonth(String tmonth)
    {
        String [] months={"January","February","March","April","May","June",
            "July","August","September","October","November","December"};
        int i;
        for(i=0;i<months.length;i++)
            if(tmonth.equals(months[i]))
                break;
        if(i<months.length)
            return true;//
        else
            return false;//
    }
    
    private void jTextField12FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField12FocusLost
        // TODO add your handling code here:
        if(verifyMonth(jTextField12.getText()))
            jTextField12.setBackground(Color.white);
        else
            jTextField12.setBackground(Color.red);
    }//GEN-LAST:event_jTextField12FocusLost

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:
            if(isInteger(jTextField11.getText()) == false)
                jTextField11.setBackground(Color.red);
            else
                jTextField11.setBackground(Color.white);
        
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
            if(isInteger(jTextField1.getText()) == true)
            {
                if(Integer.parseInt(jTextField1.getText())<=ls.size())
                    jTextField1.setBackground(Color.red);
                else
                    jTextField1.setBackground(Color.white);
            }
            else
            {
                jTextField1.setBackground(Color.red);
                if("".equals(jTextField1.getText()))
                    jTextField1.setBackground(Color.white);
            }
        
    }//GEN-LAST:event_jTextField1FocusLost

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        String slist=new String();
        String s= new String();
        while(!verifyMonth(s))
        {
            s=JOptionPane.showInputDialog(null,"Enter name of the month :- ");
            if(!verifyMonth(s))
                JOptionPane.showMessageDialog(null,"please enter a valid month...!!!");
        }
        Customer tmp=null;
        int i=0,n=ls.size();
        System.out.println("LinkedList size "+n);
        slist="Month :- "+s+"\n";
        int j=1;
	while(i<n)
	{
            tmp=ls.get(i);
            if(s.equals(tmp.cmonth))
                slist+=""+(j++)+")  "+"No :- "+(tmp.cno+1)+"\tPh no :- "
                        +tmp.cphno+"\tAMC :- "+tmp.camcamnt+"\t        Name :- "
                        +tmp.cnm+"\n";
            i++;
	}
        if(slist.equals(""))
            jTextArea1.setText("There are no AMCs in this month ");
        else
            jTextArea1.setText(slist);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jTextField1.setToolTipText("Last added customer no is "+ls.size());
    }//GEN-LAST:event_jTextField1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
